### PR TITLE
Update loop.py

### PR DESCRIPTION
**Pull request by the-dagger**
50 is too much -_-

### CODE REVIEW

**Comment by olivieer** [comment]
Nope :)

**Comment by the-dagger** [comment]
Fuck you oli :)

**Comment by Abhinav1997** [comment]
That being said, 50 indeed is too much. 30 sounds reasonable?

**Comment by the-dagger** [comment]
Make it half of original.
25.

**Comment by olivieer** [comment]
25-30 sounds good (Y)

**Pull request closed without merging**
